Algoritmo "Atividade5"
// Disciplina   : [Linguagem e Lógica de Programação]

//Desenvolva um pseudoc´odigo que solicite dois n´umeros ao usu´ario, calcule a soma
//entre eles e mostre o resultado da soma.

Var
   a, b: real
   
Inicio
   escreval("Digite um numero: ")
   leia(a)
   escreval("Digite outro numero: ")
   leia(b)
   
   escreval("O resultado é :", a + b)

Fimalgoritmo